apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwarden
  namespace: pgdump
spec:
  organizationId: "67133d60-9c46-4fe4-8e26-b1e001633fd7"
  secretName: bitwarden
  onlyMappedSecrets: true # default is true
  map:
    - bwSecretId: 36cc39d5-ecbd-4459-9f9b-b3f3004d53a9
      secretKeyName: db-001_password
    - bwSecretId: ed8621cd-07b7-48cc-a182-b3f9003c84cc
      secretKeyName: discord_webhook_url
  authToken:
    secretName: bw-auth-token
    secretKey: token
