apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: system
  source:
    repoURL: 'https://metallb.github.io/metallb'
    chart: metallb
    targetRevision: 0.16.1
    helm:
      values: |
        frrk8s:
          enabled: false
        speaker:
          frr:
            enabled: false
          ignoreExcludeLB: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
